---
- name: Install required packages
  loop:
    - postfix
    - postfix-pcre
    - mailutils
    - bsd-mailx
  package:
    name: "{{ item }}"
    state: present
  tags:
    - smtp

- name: Write aliases config
  notify:
    - Update aliases
  template:
    src: aliases.j2
    dest: /etc/aliases
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - smtp

- name: Write destinations config
  notify:
    - Restart postfix
  template:
    src: destinations.j2
    dest: /etc/postfix/destinations.cf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - smtp

- name: Write dynamicmap config
  notify:
    - Restart postfix
  template:
    src: dynamicmaps.j2
    dest: /etc/postfix/dynamicmaps.cf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - smtp

- name: Write main config
  notify:
    - Restart postfix
  template:
    src: main.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - smtp

- name: Write master config
  notify:
    - Restart postfix
  template:
    src: master.j2
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - smtp

- name: Start postfix service
  systemd:
    name: postfix
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - smtp

...
