# Standards: 1.2
---
- name: Reload postfix
  systemd:
    name: postfix
    state: reloaded
    daemon_reload: True

- name: Restart postfix
  systemd:
    name: postfix
    state: restarted
    daemon_reload: True

- name: Update aliases
  command: newaliases

...
